---
title: "Zusammenfassung vom 6. November 2017"
author: "dag.tanneberg@uni-potsdam.de"
date: "20 November 2017"
output:
  beamer_presentation:
    includes:
      in_header: header.tex
    theme: "Berlin"
    fonttheme: "professionalfonts"
    colortheme: "seagull"
    toc: false
---


# Fragestellungen

1. Worum geht es bei der Theorie der rationalen Wahl?
2. Welche Annahmen trifft die Theorie der rationalen Wahl?
3. Wie hilft mir das weiter?

# Worum geht es bei der Theorie der rationalen Wahl?

## **Zentrale Behauptung**

- Individuen wägen Vor- und Nachteile einer Handlung ab
- Wahl des besten Mittels zur Verfolgung eines Zwecks

## **Rationales Handeln...**
- verfährt instrumentell;
- erfolgt zielgerichtet und vorausschauend;
- optimiert;
- wertet Information bestmöglich aus;
- ist plantreu;
- reflektiert Präferenzen und Restriktionen.

# Welche Annahmen trifft die Theorie der rationalen Wahl?

## **Analytik einer Entscheidungssituation**
1. Akteur(e)
2. Handlungsoptionen: Mittel
3. Handlungsfolgen: Zwecke
4. Beliefs: Welches Mittel führt zu welchem Zweck?
5. Präferenzen über Handlungsfolgen

# Welche Annahmen trifft die Theorie der rationalen Wahl?

- Wahl einer Handlungsoption
    - erklärt sich logisch aus Präferenzen über Handlungsfolgen
    - setzt eine kohärente Präferenzordnung voraus

\begin{figure}[t]
\centering
\begin{tikzpicture}[grow = right, level distance = 1em, sibling distance = 4em, background rectangle/.style = {fill = grey538, draw = black}, show background rectangle]
% node placement
\node (0) [draw, shape = circle, fill = black, inner sep = 0.1em] {}
  child { node  (0-1) {} edge from parent [-latex]}
  child { node (0-2) {} edge from parent [-latex] }
;
% label placement
\node [left = 0em and 0em of 0] {
  \begin{tabular}{l}
  \textbf{Präferenz-}\\
  \textbf{ordnung}
  \end{tabular}
} ;
\node (l1) [right = 0em and 0em of 0-2] {
  \begin{tabular}{l}
    \textbf{Vollständigkeit}\\
    $\bullet$ erschöpfender Vergleich\\
    $\bullet ~ \forall ~ i, j \in I: i \ge j \lor i \le j \lor i \le j$\\
  \end{tabular}
} ;
\node (l2) [right = 0em and 0em of 0-1] {
  \begin{tabular}{l}
    \textbf{Transitivität} \\
    $\bullet$ widerspruchsfreie Ordnung \\
    $\bullet ~ \forall ~ i, j, k \in I: i \ge j \land j \ge k \implies i \ge k$ \\
  \end{tabular}
} ;
\end{tikzpicture}
\end{figure}

# Wie hilft mir das alles weiter?

1. Bietet eine belastbare Analytik von Interaktionszusammenhängen
    - Wer verfolgt welche Zwecke?
    - Welche Mittel setzt der Akteur wahrscheinlich ein?
2. Fördert die Bildung widerspruchsfreier Theorien
    - Zwingt zu transparenten Annahmen
    - Fördert annahmentreue Argumentation
3. Vielseitig einsetzbar
    - Analysiert Ein- und Mehrpersonenzusammenhänge
    - Bietet ein Portfoliot von Standardproblemen (z.B. Gefangenendil.)
    
