---
title: "Zusammenfassung vom 23. Oktober 2017"
author: "dag.tanneberg@uni-potsdam.de"
date: "30 Oktober 2017"
output:
  beamer_presentation:
    includes:
      in_header: header.tex
    theme: "Berlin"
    fonttheme: "professionalfonts"
    colortheme: "seagull"
    toc: false
---

# Fragen der Sitzung

1. Was ist Wissenschaft?
2. Wie läuft Wissenschaft ab?
3. Warum betont die Wissenschaft Falsifikation?
4. Welche Grenzen hat Falsifikation?

# Was ist Wissenschaft?

- kritische Methode des vorläufigen Erkenntnisgewinns
- Wesentliche Merkmale:
    1. Suche nach neuen Implikationen
    2. Versuch der Falsifikation
    3. Test konkurrierender Hypothesen

# Wie läuft Wissenschaft ab?

\begin{adjustbox}{max totalsize={.9\textwidth}{.9\textheight},center}\begin{tikzpicture}
\def \n {5}
\def \radius {6em}
\def \margin {8} % margin in angles, depends on the radius
\foreach \s in {1,...,\n}
{
  \node [draw, circle, fill = white!75!blue](\s) at ({-360/\n * (\s - 1)}:\radius) {$\s$};
  \draw[<-, >=latex] ({360/\n * (\s - 1)+\margin}:\radius) 
    arc ({360/\n * (\s - 1)+\margin}:{360/\n * (\s)-\margin}:\radius);
}
\node [right = of 2] {
  \begin{tabular}{l}
    \underline{Theorie}\\
    $\bullet$ Widerspruchsfreiheit\\
    $\bullet$ mind. 1 emp. Implikation\\
  \end{tabular}
} ;
\node [left = of 3] {
  \begin{tabular}{l}
    \underline{Hypothese(n)}\\
    $\bullet$ falsifizierbar\\
    $\bullet$ möglichst zahlreich\\
  \end{tabular}
} ;
\node [left = of 4] {
  \begin{tabular}{l}
    \underline{Hypothesentest}\\
    $\bullet$ möglichst vielfältig\\
    $\bullet$ möglichst kritisch\\
  \end{tabular}
} ;
\node [right = of 5] {
  \begin{tabular}{l}
    \underline{Evaluation}\\
    $\bullet$ Theorie zurückweisen?\\
    $\bullet$ Neue Fragestellung?\\
  \end{tabular}
} ;
\node [right = of 1] {
  \begin{tabular}{l}
    \underline{Fragestellung}\\
    $\bullet$ Motivation\
  \end{tabular}
} ;
\end{tikzpicture}
\end{adjustbox}

# Warum betont die Wissenschaft Falsifikation?

- i.d.R. Induktionsschluss von Daten auf allgemeine Theorien
- Induktionsschluss nicht abschließend beweisbar
- Falsifikation logisch eindeutiger

\begin{table}
\centering
\begin{tabular}{*{3}{c}}
\toprule
\textbf{H}ypothese & \textbf{D}aten & \textbf{H} $\implies$ \textbf{D} \\ \midrule
W & W & \color{green!50} W\\
W & F & \color{blue!50} F\\
F & W & \color{green!50} W\\ 
F & F & W\\
\bottomrule
\multicolumn{3}{l}{Legende: {\color{green!50} $\bullet$} Bestätigung {\color{blue!50} $\bullet$} Falsifikation.}
\end{tabular}
\end{table}

# Welche Grenzen hat Falsifikation?

1. **Beziehung zw. Hypothesen und Theorien ambivalent**:
  Eine Theorie generiert viele Hypothesen. Dieselbe
  Hypothese folgt aus vielen Theorien. Strikte Falsifikation
  ist unmöglich.
2. **Messungen sind fehleranfällig**: Haben wir ein
  kontradiktorisches Ereignis beobachtet?
3. **Hypothesen i.d.R. kontinuierlich**: Meistens
      interessieren nicht diskrete Unterschiede sondern
      Häufigkeitsverteilungen.
4. **Falsifikation ist konsensuell**: Wissenschaft ist ein
  soziales Unternehmen, die Zurückweisung von Theorien
  erfolgt konsensuell.
