---
output:
  beamer_presentation:
    includes:
      in_header: universal_header.tex
    theme: "Berlin"
    fonttheme: "professionalfonts"
    colortheme: "seagull"
    toc: false
---

\subtitle{Einführung}
\date{8. April 2019}

\maketitle

## Ein Vorgeschmack

[Gelbwesten gegen Macron | ARTE Re: Doku](https://youtu.be/GeMb_XchnwE)

**Diskussionsfragen**

- Warum protestieren die Gelbwesten?
- Wie protestieren die Gelbwesten?
- Wie reagiert die französische Politik?
- Warum kommt es im Umfeld der Proteste zu Gewalt?
- Wie wird die Gewalt bewertet?


## Inhalte

1. Worum geht es hier eigentlich?
    - Entwicklung des Feldes, Konzepte sozialer Bewegungen
2. Warum entstehen soziale Bewegungen?
    - Ressourcen, Kollektives Handeln, Political Process, Kultur(?)
3. Formen, Strategien und Entwicklung des politischen Protests
    - Temporale Dynamiken, Verhaltensrepertoire, Reaktionen
4. Zwei Fallbeispiele
    - Demokratisierung in Portugal, Ziviler Widerstand (+ Internet?)


## Leistungsanforderungen

1. Regelmäßige, aktive Teilnahme
    - Mit*lesen*, Mit*denken*, Mit*reden*
2. *alle*: 1 Diskussionspapier
    - Vertiefende Auseinandersetzung mit einer Seminarsitzung
    - Abgabe: spätestens 14 Tage nach der Sitzung auf Moodle
    - Umfang: 750 Wörter ($\pm 10\%$)
3. *ECTS*: Hausarbeit
    - schnellstmögliche Bekanntgabe zweier Themen zur Auswahl
    - Abgabe: bis 30. September 2019 als PDF auf Moodle
    - Umfang: 3000 Wörter ($\pm 10\%$)

- Formale Gestaltung:
    [Webseite des Lehrstuhls](https://www.uni-potsdam.de/fileadmin01/projects/vergleichende-politikwissenschaft/Pr%C3%BCfungen/formal_guideline.pdf)
- Literaturverwaltung:
    [Campuslizenz Citavi](https://www.uni-potsdam.de/de/zim/angebote-loesungen/software-campuslizenzen/campuslizenz-citavi.html) oder [Zotero](https://www.zotero.org/)


## Moodle

**Titel des Kurses**: Bewegung_19

**Einschreibeschlüssel**: 3dh9Dg4j

Beachtet die Groß- und Kleinschreibung!


## Sprechstunde

**Zeitpunkt**: jeden Montag von 15.00 bis 17.00 Uhr

**Ort**: Campus Griebnitzsee, Haus 1, R.1.44

**Anmeldung**: per Email an dag.tanneberg@uni-potsdam.de
