---
title: "Zusammenfassung vom 20. November 2017"
author: "dag.tanneberg@uni-potsdam.de"
date: "27 November 2017"
output:
  beamer_presentation:
    includes:
      in_header: header.tex
    theme: "Berlin"
    fonttheme: "professionalfonts"
    colortheme: "seagull"
    toc: false
---

# Fragen der Sitzung

1. Welcher politischen Logik folgt der Parlamentarismus?
2. Welche Rolle spielt der Premieminister?
3. Wie arbeitet das Kabinett?

# Welcher politischen Logik folgt der Parlamentarismus?

- **Repräsentation**: Delegation polit. Macht
- **Problem**: Wie zieht man eine Regierung zur Verantwortung?
- **Varianten repräsentativer Demokratie**:

\begin{columns}
\begin{column}{.5\textwidth}
\begin{block}{\textbf{1. Parlamentarismus}}
\begin{tikzpicture}[grow = up, edge from parent/.style={draw,-latex}]
\node (0) [shape = rectangle, fill = white] {Staatsbürger}
  child{ node (1) [shape = rectangle, fill = white] {Parlament}
    child{node (2) [shape = rectangle, fill = white] {Regierung} }
  } ;
\node (3) at ($(1)!0.5!(2)-(2.5,0)$) [shape = rectangle, fill = white] {Verwaltung};
\node (l1) at ($(0)!0.5!(1)+(.6,0)$) {\small wählt};
\node (l2) at ($(1)!0.5!(2)+(1.1,0)$) {
  \small
  \begin{tabular}{l}
    hält polit.\\
    verantwortl.
  \end{tabular}
};
\node (l1) at ($(2)!0.5!(3)-(0.5,-.25)$) {\small leitet};
\draw [-latex] (2)--(3);
\end{tikzpicture}
\end{block}
\end{column}
\begin{column}{.5\textwidth}
\begin{block}{\textbf{2. Präsidentialismus}}
\begin{tikzpicture}[grow = up, sibling distance = 6em, edge from parent/.style={draw,-latex}]
\node (0) [shape = rectangle, fill = white] {Staatsbürger}
  child [level distance = 8em] { node (1) [shape = rectangle, fill = white] {Parlament} }
  child [level distance = 8em] { node (2) [shape = rectangle, fill = white] {Präsident} 
    child [grow = south west, level distance = 3.5em] { node (3) [shape = rectangle, fill = white] {Kabinett}
      child [grow = south] {node (4) [shape = rectangle, fill = white] {Verwaltung} }
    }
  } ;
\node (l1) at ($(0)!0.5!(1)-(.6,0)$) {\small wählt} ;
\node (l2) at ($(2)!0.5!(3)-(0.7,-0.05)$) {\small ernennt} ;
\node (l3) at ($(3)!0.5!(4)-(0.5,0)$) {\small leitet} ;
\end{tikzpicture}
\end{block}
\end{column}
\end{columns}

# Welcher politischen Logik folgt der Parlamentarismus?

**Zentral**: Reg. vom Parl. aus *politischen* Gründen abberufbar

1. Regierung existentiell von einer diszipl. Parlamentsmehrheit abh.
2. Gewaltenverschränkung zwischen Parlament und Regierung
3. wesentl. polit. Konflikt zw. Regierungsmehrheit & Opposition

# Vertrauensverhältnis v. Regierung & Parlament

1. Investiturabstimmung
  - Amtsantritt d. Regierung erfordert Mehrheitsvotum
  - nicht in allen parlamentarischen Systemen üblich
2. Misstrauensvotum
  - Parlament entzieht Regierung das Vertrauen
  - Variante: Konstruktives Misstrauensvotum
3. Vertrauensfrage
  - Regierung fordert Vertrauensaussprache des Parlaments
  - häufige Koppelung mit einer Sachfrage 

# Wie arbeitet das Kabinett?

- **Kabinett**
    - Premierminister & Minister
    - Politische Spitze der Exekutive
- **Konkurrierende Handlungslogiken**
    - Ressortprinzip: Minister führen ihr Haus selbständig
    - Kollegialprinzip: Kabinettsmitgl. verantworten Politik gemeinsam
- **Regierungspraxis**
    - Arbeitsteilige Politikgestaltung
    - Intervention nur bei besonderen Interessenskonflikten




