---
output:
  beamer_presentation:
    includes:
      in_header: universal_header.tex
    theme: "Berlin"
    fonttheme: "professionalfonts"
    colortheme: "seagull"
    toc: false
---

\subtitle{Einführung}
\date{8. April 2019}

\maketitle

## Warum Vergleichende Politikwissenschaft?

Über den bevorstehenden *Brexit* erzählt die politische Öffentlichkeit gern
die Geschichte von einer führungsschwachen Premierministerin, die an den
Hardlinern in ihrer eigenen Partei und an der Kompromissunwilligkeit der
politischen Opposition scheitert. Wie können wir dieses Deutungsangebot
differenzieren?

## Inhalte

1. Grundlagen der Vergleichenden Politikwissenschaft
    - empirisch-analytische Wissenschaft, Vergleich polit. Regime
2. Theorie der rationalen Wahl
    - Grundlagen, Anwendungen und Erweiterungen
3. Politischer Wettbewerb
    a. Konzeptualisierung (Räuml. Wettbewerb, Parteiprogramme)
    b. Determinanten (Wahl- & Regierungssysteme)
    c. Grenzen (Föderalismus, Verfassungsgerichtsbarkeit)

## Leistungsanforderungen

1. Regelmäßige, aktive Teilnahme\newline
    $\rightarrow$ Mit*lesen*, Mit*denken*, Mit*reden*
2. *alle*: 1 Diskussionspapier
    - Bekanntgabe des Themas: 13.05.
    - Abgabe: bis 27.05. als PDF auf Moodle
    - Umfang: 750 Wörter ($\pm 10\%$)
3. *ECTS*: Hausarbeit
    - schnellstmögliche Bekanntgabe zweier Themen zur Auswahl
    - Abgabe: bis 30. September 2019 als PDF auf Moodle
    - Umfang: 3000 Wörter ($\pm 10\%$)

- Formale Gestaltung:
    [Webseite des Lehrstuhls](https://www.uni-potsdam.de/fileadmin01/projects/vergleichende-politikwissenschaft/Pr%C3%BCfungen/formal_guideline.pdf)
- Literaturverwaltung:
    [Campuslizenz Citavi](https://www.uni-potsdam.de/de/zim/angebote-loesungen/software-campuslizenzen/campuslizenz-citavi.html) oder [Zotero](https://www.zotero.org/)

## Moodle

**Titel des Kurses**: grundl_vgl_19

**Einschreibeschlüssel**: (vKG4?es

Beachtet die Groß- und Kleinschreibung!

## Sprechstunde

**Zeitpunkt**: jeden Montag von 15.00 bis 17.00 Uhr

**Ort**: Campus Griebnitzsee, Haus 1, R.1.44

**Anmeldung**: per Email an dag.tanneberg@uni-potsdam.de
